### ISSUE TITLE
Issue inferring wavedrom type from file extensions

### ISSUE THREAD

**Issue by albertschulz** [yuzutech/kroki-cli#14]
I guess there might be a dot missing here?
https://github.com/yuzutech/kroki-cli/blob/b802f44b870d62cdd631f2dfd6bd9af056778728/cmd/convert.go#L249

**Comment by ggrossetie** [comment]
Hi @albertschulz 

You are correct, nice catch!
Would you like to submit a pull request to fix this issue? You should also add a test in here to make sure that it's actually working: https://github.com/yuzutech/kroki-cli/blob/b802f44b870d62cdd631f2dfd6bd9af056778728/cmd/convert_test.go#L62

Thanks!
