### ISSUE TITLE
Package `github.com/pkg/errors` is unmaintained

### ISSUE THREAD

**Issue by folliehiyuki** [yuzutech/kroki-cli#33]
The repository is archived upstream. See the issue here https://github.com/pkg/errors/issues/245.

I think this also affects [kroki-go](https://github.com/yuzutech/kroki-go) project.

**Comment by ggrossetie** [comment]
What do you suggest as an alternative?
It seems that Go 2 *might* address this "issue" but I don't know when this version will be released: https://go.googlesource.com/proposal/+/master/design/go2draft-error-handling.md

**Comment by folliehiyuki** [comment]
From what I see from the linked thread above, other projects either implement their own methods or live within the constraint of what the standard library provides.

I'm not a Go developer though, so I honestly don't know what we should do.
